# Generated by Django 5.2.7 on 2026-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_amount_paid_order_date_ordered_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shopping_address',
            new_name='shipping_address',
        ),
    ]
